theme: minima
title: Old timeR and ever new ways to code 
author: Matthieu B. Gousseff,
description: I learned R through applied statistics 25 years ago. Back in academics after a long hiatus, I try to improve the way I code. 
